project:
  name: Secrover
domains:
  - secrover.xstar97.com
repos:
  - url: https://github.com/xstar97/home-ops.git
    branch: main
    description: Home-Ops IaC GitOps
  - url: https://github.com/xstar97/rompatcherjs.git
    branch: main
    description: RomPatcher.js
  - url: https://github.com/xstar97/apod.git
    branch: main
    description: APOD project
  - url: https://github.com/xstar97/go-littlelinks-generator.git
    branch: main
    description: GO LittleLinks Generator
